spring:
  application:
    name: myblog

  datasource:
    url: jdbc:mysql://localhost:3306/blogdb?serverTimezone=Asia/Seoul
    username: psb3505
    password: zcbadg19487.
    driver-class-name: com.mysql.cj.jdbc.Driver

